---
title: "SBC for brms models"
output: html_notebook
---

```{r}
library(SBC)
library(brms)
library(ggplot2)
options(brms.backend = "cmdstanr")
```

```{r}
data = data.frame(y = rep(0, 15), x = rnorm(15))
priors <- prior(normal(0,1), class = "b") +
  prior(normal(0,1), class = "Intercept") +
  prior(normal(0,1), class = "sigma")
generator <- brms_SBC_generator(y ~ x, data = data, prior = priors)
#brms::get_prior(y ~ x, data = data, priors = prior(normal(0,1), class = "b"))                                
```

```{r}
datasets <- generate_datasets(generator, 20)
```

```{r}
# Reuse the compiled model and other info from the generator
backend <- brms_SBC_backend_from_generator(generator, warmup = 500, iter = 1000, chains = 1,
                            init = 0.1)

# More verbose alternative:
#backend <- brms_SBC_backend(y ~ x, data = data, prior = priors, warmup = 500, iter = 1000, chains = 1,
#                            init = 0.1)
```

```{r}
results <- compute_results(datasets, backend, thin_ranks = 10)
```

```{r}
for(p in colnames(results$ranks)) {
  print(plot_ecdf_diff(results, p) + ggtitle(p))
}
```

## A failing model

```{r}
data_fail = data.frame(y = rep(0, 15), x = rnorm(15), id = 1:15, id2 = 1:15)
priors_fail <- prior(normal(0,1), class = "b") +
  prior(normal(0,10), class = "Intercept") +
  prior(normal(0,10), class = "sigma") +
  prior(normal(0,10), class = "sd")


generator_fail <- brms_SBC_generator(y ~ x + (1 | id)  + (1 | id2), data = data_fail, prior = priors_fail)
```

```{r}
datasets_fail <- generate_datasets(generator_fail, 40)
```

```{r}
# Reuse the compiled model and other info from the generator
backend_fail <- brms_SBC_backend_from_generator(generator_fail, warmup = 500, iter = 1000, chains = 1,
                            init = 0.1)

# More verbose alternative:
#backend <- brms_SBC_backend(y ~ x, data = data, prior = priors, warmup = 500, iter = 1000, chains = 1,
#                            init = 0.1)
```

```{r}
results_fail <- compute_results(datasets_fail, backend_fail, thin_ranks = 5)
```

We see a problem with `sigma`. Notably the problem is also visible when looking at `lp__` (which we would expect to often manifest problems if at least one of the parameters has problems)

```{r}
for(p in c("sigma", "lp__")) {
  print(plot_ecdf_diff(results_fail, p) + ggtitle(p))
}
```
