---
title: "Model interaction"
output: html_document
---

```{r setup}
library(SBC)

# use_cmdstanr <- TRUE # Set to false to use rstan instead
# 
# if(use_cmdstanr) {
#   library(cmdstanr)
# } else {
#   library(rstan)
# }
library(cmdstanr)
library(bayesplot)
library(posterior)

library(future)
plan(multisession) 

options(SBC.min_chunk_size = 5)
```

Three models of simple.stan from "ryanbe.me", indexed in order of choice from the tree graph. To define model correlation score the following should be inspected: symmetry, triangular inequality, 
```{r simple}
backend_1_1 <- cmdstan_sample_SBC_backend(cmdstan_model("model_interaction/simple1_1.stan"))
backend_1_2 <- cmdstan_sample_SBC_backend(cmdstan_model("model_interaction/simple1_2.stan"))
backend_2_1 <- cmdstan_sample_SBC_backend(cmdstan_model("model_interaction/simple2_1.stan"))
# backend_2_2 <- cmdstan_sample_SBC_backend(cmdstan_model("model_interaction/simple2_2.stan")) doesn't have any parameter
```

```{r }
generator_func_1_1 <- function(N) {
  sigma <-  rlnorm(1);
  mu <- rnorm(1);
  y <- rnorm(N, mu, sigma);
  list(
    parameters = list(
      mu = mu,
      sigma = sigma
    ),
    generated = list(
      N = N,
      y = y
    )
  )
}
generator_func_1_1 <- function_SBC_generator(generator_func_1_1, N = 50)
dataset_1_1 <- generate_datasets(generator_func_1_1, n_datasets = 10)
```

```{r }
generator_func_1_2 <- function(N) {
  sigma <-  rexp(1)
  mu <- rnorm(1)
  y <- rnorm(N, mu, sigma)
  list(
    parameters = list(
      mu = mu, 
      sigma = sigma
    ),
    generated = list(
      N = N,
      y = y
    )
  )
}
generator_func_1_2 <- function_SBC_generator(generator_func_1_2, N = 50)
dataset_1_2 <- generate_datasets(generator_func_1_2, 10)
```

```{r }
generator_func_2_1 <- function(N) {
  sigma <-  rlnorm(1) # from parameter block
  mu <- 0 # from transformed parameter block
  y <- rnorm(N, mu, sigma) #not sure between rnorm(N, 0, sigma)
  list(
    parameters = list(
      mu = mu,
      sigma = sigma
    ),
    generated = list(
      N = N,
      y = y
    )
  )
}
generator_func_2_1 <- function_SBC_generator(generator_func_2_1, N = 50)
dataset_2_1 <- generate_datasets(generator_func_2_1, 10)
```

```{r }
# How would the degree of neighbor affect the correlation score between two models? Following questions are in order
# 1. Would there exist any stats s.t. results_i_j_i_j+1$stat < results_i_j_!(i_j) for all i_j paris?
# 2. Would symmetric? triangular inequality?
results_1_1_1_1 <- compute_results(dataset_1_1, backend_1_1)
results_1_1_1_2 <- compute_results(dataset_1_1, backend_1_2)
results_1_1_2_1 <- compute_results(dataset_1_1, backend_2_1)

results_1_2_1_2 <- compute_results(dataset_1_2, backend_1_2)
results_1_2_1_1 <- compute_results(dataset_1_2, backend_1_1)
results_1_2_2_1 <- compute_results(dataset_1_2, backend_2_1)

results_2_1_2_1 <- compute_results(dataset_2_1, backend_2_1)
results_2_1_1_1 <- compute_results(dataset_2_1, backend_1_1)
results_2_1_1_2 <- compute_results(dataset_2_1, backend_1_2)
```

```{R}
plot_ecdf_diff(results_1_1_1_1)
plot_ecdf_diff(results_1_1_1_2)
plot_ecdf_diff(results_1_1_1_1)
plot_ecdf_diff(results_1_2_1_2)
plot_ecdf_diff(results_1_2_1_1)
plot_ecdf_diff(results_1_2_2_1)
plot_ecdf_diff(results_2_1_2_1)
plot_ecdf_diff(results_2_1_1_1)
plot_ecdf_diff(results_2_1_1_2)
```
