---
title: "Introduction to SBC visualisations"
author: "Martin Modrák"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SBC visualisations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette aims to explain how to interpret various visualisations of
the main results of SBC: the posterior ranks.


```{r setup, message=FALSE,warning=FALSE, results="hide"}
library(bayesplot)
library(SBC)
library(ggplot2)
knitr::opts_chunk$set(fig.width = 3, fig.height = 2)
```


```{r rank_hist}
set.seed(216456)

max_rank <- 100
N_ranks <- 200

rank_dfs <- list(
  data.frame(parameter = "beta", dataset_id = 1:N_ranks, rank = round(rbeta(N_ranks, shape1 = 1, shape2 = 1) * max_rank)),
  data.frame(parameter = "beta", dataset_id = 1:N_ranks, rank = round(rbeta(N_ranks, shape1 = 0.5, shape2 = 0.5) * max_rank)),
  data.frame(parameter = "beta", dataset_id = 1:N_ranks, rank = round(rbeta(N_ranks, shape1 = 2, shape2 = 2) * max_rank)),
  data.frame(parameter = "beta", dataset_id = 1:N_ranks, rank = round(rbeta(N_ranks, shape1 = 5, shape2 = 2) * max_rank)),
  data.frame(parameter = "beta", dataset_id = 1:N_ranks, rank = round(rbeta(N_ranks, shape1 = 1, shape2 = 2) * max_rank))
)

plot_rank_hist(rank_dfs[[1]], max_rank = max_rank) + ggtitle("Uniform")
plot_rank_hist(rank_dfs[[2]], max_rank = max_rank) + ggtitle("Model too certain")
plot_rank_hist(rank_dfs[[3]], max_rank = max_rank) + ggtitle("Model too uncertain")

plot_rank_hist(rank_dfs[[4]], max_rank = max_rank) + ggtitle("Model underestimating")
plot_rank_hist(rank_dfs[[5]], max_rank = max_rank) + ggtitle("Model overestimating")
```



```{r}
# plot_ecdf(rank_dfs[[1]], max_rank = max_rank) + ggtitle("Uniform")
# plot_ecdf(rank_dfs[[2]], max_rank = max_rank) + ggtitle("Model too certain")
# plot_ecdf(rank_dfs[[3]], max_rank = max_rank) + ggtitle("Model too uncertain")
# plot_ecdf(rank_dfs[[4]], max_rank = max_rank) + ggtitle("Model underestimating")
# plot_ecdf(rank_dfs[[5]], max_rank = max_rank) + ggtitle("Model overestimating")

```



```{r}
# plot_ecdf_diff(rank_dfs[[1]], max_rank = max_rank) + ggtitle("Uniform")
# plot_ecdf_diff(rank_dfs[[2]], max_rank = max_rank) + ggtitle("Model too certain")
# plot_ecdf_diff(rank_dfs[[3]], max_rank = max_rank) + ggtitle("Model too uncertain")
# 
# plot_ecdf_diff(rank_dfs[[4]], max_rank = max_rank) + ggtitle("Model underestimating")
# plot_ecdf_diff(rank_dfs[[5]], max_rank = max_rank) + ggtitle("Model overestimating")
```

