#' A mock backend.
#'
#' Mock backend is useful for testing the package.
#' It will ignore all data passed to it and always
#' provide `result` as the draws generated by the backend.
#'
#' @param result a `draws_matrix` that will be returned regardless of the data
#' @export
SBC_backend_mock <- function(result, output = NULL, message = NULL,
                             warning = NULL, error = NULL) {
  if(!posterior::is_draws_matrix(result)) {
    stop("Mock backend requires result to be draws_matrix")
  }

  structure(list(result = result,
                 output = output,
                 message = message,
                 warning = warning,
                 error = error), class = "SBC_backend_mock")
}

#' @export
SBC_fit.SBC_backend_mock <- function(backend, generated, cores) {
  if(!is.null(backend$output)) {
    cat(backend$output)
  }
  if(!is.null(backend$message)) {
    message(backend$message)
  }
  if(!is.null(backend$warning)) {
    warning(backend$warning)
  }
  if(!is.null(backend$error)) {
    stop(backend$error)
  }

  backend$result
}

